# Generated by Django 6.0.3 on 2026-05-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
