# Generated by Django 6.0.3 on 2026-07-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_starts_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("APPROVED", "Aprovado"),
                    ("REJECTED", "Rejeitado"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
